[
    {
        "nodeid": "test.py::Test1::test_with_steps",
        "testcase_uuid": "some-id-heh",
        "status": "fail",
        "startime_timestamp": 1725873490.5974107,
        "stoptime_timestamp": 1725873490.5974107,
        "duration": 0.0003747998271137476,
        "report": "self = <test.Test1 object at 0x000001E6E69688E0>\n\n    @lite.id('some-id-heh')\n    def test_with_steps(self):\n        #TestLiteStep\n        print('step: 1')\n        #TestLiteStep\n        print('step: 2')\n>       a = 5 / 0\nE       ZeroDivisionError: division by zero\n\ntest.py:47: ZeroDivisionError",
        "log": "",
        "skipreason": null,
        "precondition_status": "passed",
        "postcondition_status": "passed",
        "step_number_with_error": 2,
        "startime_readable": "2024-09-09 18:18:10.597411",
        "stoptime_readable": "2024-09-09 18:18:10.597411"
    },
    {
        "nodeid": "test.py::Test1::test_passed",
        "testcase_uuid": "a6666ac6-af09-4cdf-8835-5befd9c9f919",
        "status": "passed",
        "startime_timestamp": 1725873490.6405673,
        "stoptime_timestamp": 1725873490.6405673,
        "duration": 0.0005522000137716532,
        "report": null,
        "log": "\u001b[32mINFO    \u001b[0m test:test.py:10 its fix1 log\n\u001b[32mINFO    \u001b[0m test:test.py:56 its test_passed info 1 log\n\u001b[32mINFO    \u001b[0m test:test.py:58 its test_passed info 2 log",
        "skipreason": null,
        "precondition_status": "passed",
        "postcondition_status": "passed",
        "step_number_with_error": null,
        "startime_readable": "2024-09-09 18:18:10.640567",
        "stoptime_readable": "2024-09-09 18:18:10.640567"
    },
    {
        "nodeid": "test.py::Test1::test_from_another_class",
        "testcase_uuid": null,
        "status": "fail",
        "startime_timestamp": 1725873490.705134,
        "stoptime_timestamp": 1725873490.705134,
        "duration": 0.000448400154709816,
        "report": "self = <test.Test1 object at 0x000001E6E6968850>\n\n    def test_from_another_class(self):\n        #TestLiteStep\n        print('TEST FROM ANOTHER CLASS')\n        #TestLiteStep\n        super().another_func()\n>       assert self.value == 1\nE       assert 5 == 1\nE        +  where 5 = <test.Test1 object at 0x000001E6E6968850>.value\n\ntest.py:67: AssertionError",
        "log": "",
        "skipreason": null,
        "precondition_status": "passed",
        "postcondition_status": "passed",
        "step_number_with_error": 2,
        "startime_readable": "2024-09-09 18:18:10.705134",
        "stoptime_readable": "2024-09-09 18:18:10.705134"
    },
    {
        "nodeid": "test.py::Test1::test_with_logic_in_other_func",
        "testcase_uuid": null,
        "status": "fail",
        "startime_timestamp": 1725873490.7551904,
        "stoptime_timestamp": 1725873490.7551904,
        "duration": 0.0003787998575717211,
        "report": "self = <test.Test1 object at 0x000001E6E69685E0>\n\n    def test_with_logic_in_other_func(self):\n        #TestLiteStep\n        print('TEST WITH LOGIC IN OTHER FUNC')\n        value = self.other_func()\n        #TestLiteStep\n        log.info('its test_with_logic_in_other_func info 1 log')\n        #TestLiteStep\n>       assert value == 1\nE       assert 5 == 1\n\ntest.py:85: AssertionError",
        "log": "\u001b[32mINFO    \u001b[0m test:test.py:73 its other_func info 1 log\n\u001b[32mINFO    \u001b[0m test:test.py:83 its test_with_logic_in_other_func info 1 log",
        "skipreason": null,
        "precondition_status": "passed",
        "postcondition_status": "passed",
        "step_number_with_error": 3,
        "startime_readable": "2024-09-09 18:18:10.755190",
        "stoptime_readable": "2024-09-09 18:18:10.755190"
    },
    {
        "nodeid": "test.py::Test1::test_skip",
        "testcase_uuid": null,
        "status": "skip",
        "startime_timestamp": 1725873490.7638223,
        "stoptime_timestamp": 1725873490.7638223,
        "duration": 0.00023740017786622047,
        "report": null,
        "log": "",
        "skipreason": "Skipped: Just testing skip reason",
        "precondition_status": null,
        "postcondition_status": null,
        "step_number_with_error": null,
        "startime_readable": "2024-09-09 18:18:10.763822",
        "stoptime_readable": "2024-09-09 18:18:10.763822"
    },
    {
        "nodeid": "test.py::Test1::test_fail",
        "testcase_uuid": null,
        "status": "fail",
        "startime_timestamp": 1725873490.830491,
        "stoptime_timestamp": 1725873490.830491,
        "duration": 0.00035239988937973976,
        "report": "self = <test.Test1 object at 0x000001E6E69642B0>, fix2 = 2\n\n    def test_fail(self, fix2):\n        log.info('its test_fail info log')\n>       assert 1==fix2\nE       assert 1 == 2\n\ntest.py:95: AssertionError",
        "log": "\u001b[32mINFO    \u001b[0m test:test.py:15 its fix2 log\n\u001b[32mINFO    \u001b[0m test:test.py:94 its test_fail info log",
        "skipreason": null,
        "precondition_status": "passed",
        "postcondition_status": "passed",
        "step_number_with_error": null,
        "startime_readable": "2024-09-09 18:18:10.830491",
        "stoptime_readable": "2024-09-09 18:18:10.830491"
    },
    {
        "nodeid": "test.py::Test1::test_error_in_setup",
        "testcase_uuid": null,
        "status": "error",
        "startime_timestamp": 1725873490.8720522,
        "stoptime_timestamp": 1725873490.8720522,
        "duration": 0.00039760000072419643,
        "report": "@pytest.fixture\n    def fix_error():\n        log.info(f'NOW WE MAKE ERROR')\n>       a = 5 / 0\nE       ZeroDivisionError: division by zero\n\ntest.py:21: ZeroDivisionError",
        "log": "\u001b[32mINFO    \u001b[0m test:test.py:20 NOW WE MAKE ERROR",
        "skipreason": null,
        "precondition_status": "error",
        "postcondition_status": "passed",
        "step_number_with_error": null,
        "startime_readable": "2024-09-09 18:18:10.872052",
        "stoptime_readable": "2024-09-09 18:18:10.872052"
    },
    {
        "nodeid": "test.py::Test1::test_error_in_test",
        "testcase_uuid": null,
        "status": "fail",
        "startime_timestamp": 1725873490.9153762,
        "stoptime_timestamp": 1725873490.9217668,
        "duration": 0.00035859993658959866,
        "report": "self = <test.Test1 object at 0x000001E6E6964F10>\n\n    def test_error_in_test(self):\n        log.info('its test_error_in_test info log')\n>       a = 5 / 0\nE       ZeroDivisionError: division by zero\n\ntest.py:103: ZeroDivisionError",
        "log": "\u001b[32mINFO    \u001b[0m test:test.py:102 its test_error_in_test info log",
        "skipreason": null,
        "precondition_status": "passed",
        "postcondition_status": "passed",
        "step_number_with_error": null,
        "startime_readable": "2024-09-09 18:18:10.915376",
        "stoptime_readable": "2024-09-09 18:18:10.921767"
    },
    {
        "nodeid": "test.py::Test1::test_error_in_teardown",
        "testcase_uuid": "some-id",
        "status": "passed",
        "startime_timestamp": 1725873490.956593,
        "stoptime_timestamp": 1725873490.956593,
        "duration": 0.0019112001173198223,
        "report": null,
        "log": "\u001b[32mINFO    \u001b[0m test:test.py:108 its fix_error_teardown info log",
        "skipreason": null,
        "precondition_status": "passed",
        "postcondition_status": "error",
        "step_number_with_error": null,
        "startime_readable": "2024-09-09 18:18:10.956593",
        "stoptime_readable": "2024-09-09 18:18:10.956593"
    }
]